name: First Workflow 
on: workflow_dispatch # manually start the workflow 
jobs: 
  first-job: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Print hello 
        run: echo "Hello World"
      - name: Print goobye 
        run: echo "Done - bye!"
